title: Julien Chomarat
description: > 
  Everything about development & geek stuff.
permalink: ':title/'
baseurl: ""
url: ""
site-twitter:

# Author Settings
author: Julien Chomarat # add your name
author-img: jchomarat.jpg # add your photo
about-author: Actor, dancer, writer, investor ... nah, just a developer sharing his experience!
social-twitter: jchomarat
social-facebook: # add your Facebook handle
social-github: jchomarat # add your Github handle
social-linkedin: julienchomarat
social-email: 

# Hang loose
hangLoose-azStorage: jsharedstorage 
hangLoose-azStorageSas: ?sv=2019-10-10&ss=t&srt=sco&sp=rwdlacu&se=2025-06-17T20:48:24Z&st=2020-06-17T12:48:24Z&spr=https&sig=YbFqXn4zrivjoAhNZsvUljlfxC2%2BgcLs8z%2FxWu%2B%2BOXo%3D
hangLoose-azStorageTableName: blogHangloose

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
