title: Julien Chomarat
description: > 
  Everything about development & geek stuff.
permalink: ':title/'
baseurl: ""
url: ""
site-twitter:

# Author Settings
author: Julien Chomarat
author-img: jchomarat.jpg
about-author: Actor, dancer, writer, investor ... nah, just a developer sharing his experience!
social-twitter: jchomarat
social-facebook: 
social-github: jchomarat
social-linkedin: julienchomarat
social-email: 

# Hang loose
hangLoose-azStorage: jsharedstorage 
hangLoose-azStorageSas: ?sv=2019-10-10&ss=t&srt=sco&sp=rwacu&se=2025-06-17T20:58:28Z&st=2020-06-16T12:58:28Z&spr=https&sig=3nkC7BcCDcbvCiuTDuZUF1fbQ1OyuYV22n%2FXHJHJQYM%3D
hangLoose-azStorageTableName: blogHangloose

# Tracker
analytics: 

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
