title: Julien Chomarat
description: > 
  Everything about development & geek stuff.
permalink: ':title/'
baseurl: ""
url: ""
site-twitter:

# Author Settings
author: Julien Chomarat # add your name
author-img: jchomarat.jpg # add your photo
about-author: Actor, dancer, writer, investor ... nah, just a developer sharing his experience!
social-twitter: jchomarat
social-facebook: # add your Facebook handle
social-github: jchomarat # add your Github handle
social-linkedin: julienchomarat
social-email: 

# Hang loose
hangLoose-azStorage: juchoblogstorage 
hangLoose-azStorageSas: ?sv=2019-02-02&ss=t&srt=sco&sp=rwacu&se=2021-12-05T21:57:04Z&st=2019-12-04T13:57:04Z&spr=https&sig=QK3fx2%2BGd1a3RwsJmpQB6p%2FMbx4TaocIh6s8wI5Di4E%3D
hangLoose-azStorageTableName: blogHangLoose

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
